baseurl: https://fanggong.pub
title: Fang Yongchao
theme:  hugo-coder-portfolio
DefaultContentLanguage: ch
paginate: 25
pygmentsstyle: b2
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
pygmentsUseClasses: yes
disqusShortname:
params:
  author: Fang Yongchao
  avatarurl: images/avatar.jpg
  custom_css: []
  description: Fang Yongchao's personal website
  enableFacebookShare: no
  enableHatenaShare: no
  enableLineShare: no
  enableLinkedInShare: no
  enableTwitterShare: no
  fixedbarContent: no
  fixedbarContentAfter: no 
  footercontent: 赣ICP备 2020014401号-1
  hideCopyright: no
  hideCredits: no
  info: 不要害怕未知的事物
  itemscentered: yes
  keywords: blog, data science
  langseparator: '|'
  math: yes
  rtl: no
  snsShare: yes
  social:
    - icon: fab fa-github
      name: Github
      url: https://github.com/fanggong
      weight: 1
    - icon: fas fa-envelope
      name: Mail
      url: mailto:yongchao.fang@outlook.com
      weight: 2
    - icon: fab fa-weixin
      name: Wechat
      url: ./images/wechat.png
      weight: 3
  thumbnail: images/tn.png
languages:
  ch:
    languagecode: ch
    languagename: Chinese
    menu:
      main:
        - name: About
          url: about
          weight: 1
        - name: Blog
          url: posts
          weight: 2
        - name: Tools
          url: tools
          weight: 3
        - name: Categories
          url: categories
          weight: 4
    params:
      author: Fang Yongchao
      description: Fang Yongchao's personal website
      info: 不要害怕未知的事物
      keywords: blog, data science
    title: Connecting the dots 
