---
title: 对本主题的样式的测试
author: Fang Yongchao
date: "`r Sys.Date()`"
---

任何做个人博客的人应该都过不了对样式无穷无尽的修改这个坎吧...

# 这是一级标题

## 这是二级标题

### 这是三级标题

### 页内跳转

[点这里跳到最重要的样式——表格](#表格)

### 无序列表

- 御田的决心！白胡子的试炼!
- 白胡子的弟弟！御田的大冒险
- 兵刃相接！罗杰与白胡子！

### 有序列表

1. 新的同盟！？凯多军大集结
1. 决战迫近！草帽一伙进入战斗状态
1. 大新闻！七武海袭击事件

### 嵌套列表

- 元气森林
  - 0糖
  - 0脂肪
  - 0卡路里

### 代码块

```{r}
height <- rnorm(100, 170, 8)
weight <- rnorm(100, 70, 12)
t.test(height, weight)
```

### 行内代码

用`data.frame()`创建数据框

### 引用

> 故人具鸡黍，邀我至田家  
> 绿树村边合，青山郭外斜  
> 开轩面场圃，把酒话桑麻  
> 待到重阳日，还来就菊花

### 公式块

正态分布的概率密度函数为：
$$f(x) = {1 \over {\sqrt{2\pi}\sigma}}exp \left( - {{(x - \mu)^2} \over {2\sigma^2}}  \right)$$

### 行内公式

等比数列的求和公式是$a_1(1 - q^n) \over {1-q}$

### 表格

[CRAN](https://mirrors.tuna.tsinghua.edu.cn/CRAN/web/packages/available_packages_by_date.html)中提供了相当多的对表格样式进行渲染的包，这里列出了一些对于我来说比较常用的

- `pander::pander()`
```{r echo=FALSE}
pander::pander(mtcars[1:5, 1:5])
```

```{r echo=FALSE}
library(kableExtra)
mtcars[1:5, 1:5] %>%
  kbl(caption = "Recreating booktabs style table") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```
