---
title: ggplot2使用笔记（5）—— Position
author: Fang Yongchao
date: "2021-03-26"
output:
  blogdown::html_page:
    toc: yes
    toc_depth: 2
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.align = "center", out.width = "50%")
library(ggplot2)
library(dplyr)
```

`POSITION_FUNCTION`函数作为`STAT_FUNCTION`和`GEOM_FUNCTION`函数的参数使用。

## `position = "dodge"`：并排摆放

-------------------------------

```{r}
ggplot(mpg, aes(fl, fill = drv)) + 
  geom_bar(position = position_dodge()) + 
  scale_fill_brewer(palette = 1)
```


## `position = "fill"`：填充摆放

-------------------------------

```{r}
ggplot(mpg, aes(fl, fill = drv)) + 
  geom_bar(position = position_fill()) + 
  scale_fill_brewer(palette = 1)
```

## `position = "jitter"`：抖动点

-------------------------------

```{r}
ggplot(mpg, aes(cty, hwy)) + 
  geom_point(position = position_jitter(), size = 1, alpha = 0.5) + 
  geom_point(color = "red", size = 1, alpha = 0.5)
```

## `position = "stack"`：堆栈摆放

-------------------------------

```{r}
ggplot(mpg, aes(fl, fill = drv)) + 
  geom_bar(position = position_stack()) + 
  scale_fill_brewer(palette = 1)
```

## `position = "jitterdodge"`：不是很明白实际意义

-------------------------------

```{r}
ggplot(mpg, aes(class, displ, fill = fl)) +
  geom_boxplot(alpha = 0.5) +
  geom_point(pch = 21, position = position_jitterdodge()) +
  scale_fill_brewer(palette = 1)
```
