---
title: 差异显著性检验
author: Fang Yongchao
date: "2021-05-13"
categories:
  - "统计学"
  - "R语言"
output:
  blogdown::html_page:
    toc: yes
    toc_depth: 2
---

```{r library, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, eval = FALSE)
```

下面记述的各种情况及适用的差异显著性检验的相关方法都是以样本之间相互独立为前提的。对于样本之间不相互独立的情况，应该针对具体情况使用特定的方法。

## 单样本的差异显著性分析

----------------------------

### 连续变量的单样本

对于连续变量的单样本，一般需要检验的是该样本是否取自于均值为$\mu_0$的总体，其采用的检验方法一般为**t检验**或**z检验**。根据Wikipedia，当样本量较小且样本来自于标准差未知的正态总体时，适用t检验；当样本量较大或总体方差已知时，由于中心极限定理，可以使用z检验。

（这个描述从第一次接触统计学开始就困扰着我，总体方差怎么会已知，都已知总体方差了总体均值为什么会未知）

### 无序离散变量的单样本

对于无序离散变量的单样本，一般检验的是样本所在总体中某类别占比（即率）是否等于$p_0$。在大样本下，样本率是服从正态分布的，故可以直接使用**z检验**；在小样本下，可以看作对伯努利试验（属于该类别和不属于该类别）的成功率$p$是否等于$p_0$的检验，故可以使用**精确二项检验(Exact Binomial Test)**。

### 有序离散变量的单样本

对于有序离散变量的单样本，个人认为需要根据实际目的选择检验方法。如果关注的是变量的整体的形态，可以根据变量服从的分布选择如**精确泊松检验**等，或是将有序离散变量当作连续变量，在近似服从正态分布的前提下使用**t检验**或**z检验**。如果关注的变量中类别的比例，那么可以直接将有序离散变量当作无序离散变量做对应的显著性检验。

## 两样本的差异显著性分析

----------------------------

### 连续变量的两样本

对于连续变量的两样本的差异显著性检验，可以分成下面三种情况：

- 样本均取自服从正态分布的总体且满足方差齐性，使用**t检验**
- 样本均取自服从正态分布的总体但是不满足方差齐性，使用**近似t检验**
- 样本并非均取自服从正态分布的总体，使用**Wilcoxon秩和检验**

### 无序离散变量的两样本

对于无序离散变量的两样本的差异显著性检验，需要将数据变换成列联表后进行显著性检验，检验方法可以分成以下两类：

- 变量的水平（类别数）等于2
  - 列联表中频数总和大于等于40且每个格子的期望频数均大于等于5时，使用**Pearson卡方检验**
  - 列联表中频数总和大于等于40且存在某个格子的期望频数大于等于1而小于5时，使用**连续性校正卡方检验**
  - 列联表中频数综合小于40或存在某个格子的期望频数小于1时，使用**Fisher精确检验**

- 变量的水平大于2
  - 80%以上的格子期望频数大于等于5且所有格子的期望频数均大于等于1时，使用**Pearson卡方检验**
  - 20%以上的格子期望频数小于5或存在某个格子的期望频数小于1时，使用**Fisher精确检验**

### 有序离散变量的两样本

对于有序离散变量的两样本的差异显著性检验，同样需要将数据变换成列联表后进行显著性检验，检验方法可以分成以下两类：

- 两组样本的样本量均大于50，使用**Ridit分析**
- 存在某组样本的样本量小于等于50，使用**Wilcoxon秩和检验**

## 多样本的差异显著性分析

----------------------------

### 连续变量的多样本

对于连续变量的两样本的差异显著性检验，可以分成下面两种情况：

- 样本均取自服从正态分布的总体且满足方差齐性，使用**方差分析**
- 样本并非取自服从正态分布的总体或不满足方差齐性，使用**K-W秩和检验**

### 无序离散变量的多样本

对于无序离散变量的多样本的差异显著性检验，将数据变换成列联表后进行显著性检验，检验方法可以分成以下两类：

- 80%以上的格子期望频数大于等于5且所有格子的期望频数均大于等于1时，使用**Pearson卡方检验**
- 20%以上的格子期望频数小于5或存在某个格子的期望频数小于1时，使用**Fisher精确检验**

### 有序离散变量的多样本

对于有序离散变量的多样本的差异显著性检验，将数据变换成列联表后进行显著性检验，检验方法可以分成以下两类：

- 两组样本的样本量均大于50，使用**Ridit分析**
- 存在某组样本的样本量小于等于50，使用**Wilcoxon秩和检验**

## 各检验方法的R语言实现

----------------------------

- z检验：`BSDA::z.test()`
- t检验：`t.test(var.equal = TRUE)`
- 近似t检验：`t.test()`
- Pearson卡方检验：`chisq.test(correct = FALSE)`
- 连续性校正卡方检验：`chisq.test()`
- Fisher精确检验：`fisher.test()`
- Wilcoxon秩和检验：`wilcox.test()`
- K-W秩和检验：`kruskal.test()`
- Ridit分析：`Ridit::ridit()`
- 方差分析：`aov()`
- 二项检验：`binom.test()`
- 泊松检验：`poisson.test()`


