---
title: 交易规则（v0.2)
author: Fang Yongchao
date: "2023-03-16"
categories:
  - "Crypto"
output:
  blogdown::html_page:
    toc: yes
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

1. 杠杆倍数不超过x3
1. 单个仓位开仓保证金不超过N，同一标的同一方向加仓或增加保证金后保证金不超过2N，N的初始金额为初始本金的1/8，每当总本金盈利25%或亏损20%时对N进行同比例调整
1. 开仓时下止损委托，动态调整，最大-36%止损（严守）
1. 除清仓操作外不进行市价委托

2023年3月3日 至 2023年3月15日 13天，收益率-11.77%

```{r echo=FALSE}
dat <- list(
  list(
    "open_time" = "2023/03/13 14:03:57",
    "close_time" = "2023/03/14 22:29:41",
    "currency" = "CFXUSDT 永续",
    "position_type" = "逐仓(2.0x)",
    "open_price" = "0.22185",
    "close_price" = "0.33336",
    "pnl" = "-100.53%"
  ),
  list(
    "open_time" = "2023/02/28 14:30:50",
    "close_time" = "2023/03/13 11:21:53",
    "currency" = "AGLDUSDT 永续",
    "position_type" = "逐仓(2.0x)",
    "open_price" = "0.5396",
    "close_price" = "0.3791",
    "pnl" = "-59.51%"
  )
)
```

```{r echo=FALSE}
library(kableExtra)
tmp <- function(a, b) {
  rbind(a, data.frame(b))
}
dat <- Reduce(tmp, dat)
names(dat) <- c("开仓时间", "平仓时间", "合约", "仓位类型", "开仓均价", "平仓均价", "收益率")
kbl(dat, row.names = TRUE) %>%
  kable_paper(html_font = "Fira Mono") %>%
  scroll_box(width = "100%", height = "300px")
```