name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2 

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@5.2.1
        env:
          remote_key: ${{ secrets.DEPLOY_KEY }} 
          args: -avz --delete
          remote_port: "22"
          path: ./public/
          remote_host: ${{ secrets.SSH_HOST }} 
          remote_user: ${{ secrets.SSH_USERNAME }} 
          path: /srv/blog/
          
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            systemctl restart nginx.service
